### ISSUE TITLE
Bug Report 1: If you use GNOME/GDM

### ISSUE THREAD

**Issue by Sprunglesonthehub** [cobra3282000/AcreetionOS#12]
If you use Gnome and have a bunch of text pop up when logging in, do the following:

Open A TTY and delete /etc/motd, it is just a text file with that text.

My overall recommendation: Delete /etc/motd from the source files. We don't need it necessarily.

**Comment by cobra3282000** [comment]
moved offending file, and sent it the gallows for punishment!  lol all fixed.
