### ISSUE TITLE
Other filesystems are busted.

### ISSUE THREAD

**Issue by Sprunglesonthehub** [cobra3282000/AcreetionOS#13]
The other filesystems are busted. Remove the options for everything but ext4. I recommend we talk about adding support for BTRFS and XFS, but we will need to get together to figure out what requirements it takes to add support.

**Comment by Sprunglesonthehub** [comment]
I would recommend installing xfsprogs as well as if you want XFS to work. If you want BTRFS to work, you will need to add btrfs-progs to the packages.x86_64 list

**Comment by cobra3282000** [comment]
added.
