### ISSUE TITLE
AcreetionOS Installer no internet bug

### ISSUE THREAD

**Issue by Sprunglesonthehub** [cobra3282000/AcreetionOS#4]
[](url)
![bug1](https://github.com/user-attachments/assets/483bd2aa-38ea-4227-826b-3ff4debb3520)

This shows it is not connected to the internet, but it is actually connected.
The host is connected a VPN.

Need to investigate.

**Comment by cobra3282000** [comment]
i will try and repeat the bug when i install on hardware in a bit.

**Comment by cobra3282000** [comment]
i am unable to reproduce this error, just installed on live hardware and didn't see this, also didnt see it in the VM install either.   very very strange.  but can't reproduce it.

**Comment by cobra3282000** [comment]
okay i figured this out, if you are using vm and your main system uses systemd.networking instead of networkmanager, this will happen.   systemd-networking is not a good choice because it tends to break stuff.
